$(document).ready(function(){
    $('.openModal').click(function(){
      $('.mac-window').addClass('active');
    });
    $('.close').click(function(){
      $('.mac-window').removeClass('active');
      $('.mac-window').removeClass('maximize');
      $('.mac-window').removeClass('minimize');
    });
    $('.minimize').click(function(){
      $('.mac-window').toggleClass('minimize');
      $('.mac-window').removeClass('maximize');
    });
    $('.maximize').click(function(){
      $('.mac-window').toggleClass('maximize');
      $('.mac-window').removeClass('minimize');
    });
  });