name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # concurrency:
    #   group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: '23'
          cache: 'npm'
          #check-latest: true
      - name: Install dependencies
        id: install
        run: npm install
      - name: Build
        id: build
        run: npm run build
      - name: Prepare deployment
        run: |
          mkdir -p prod
          cp -r dist prod/
          cp -r assets prod/
          cp 404.html prod/
          cp index.html prod/
      - name: Verify build
        run: ls -l
      - name: Deploy
        id: deploy
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # commit hash of v4.0.0
        #if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          # exclude_assets: '.github,.gitignore,docs/README.md'
          publish_dir: ./prod # ./public 
          cname: lynkos.dev