name: Build and deploy lynkos.dev

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'npm'
          check-latest: true
      - name: Install dependencies
        id: install
        run: npm install
      - name: Build
        id: build
        run: npm run build
      - name: Verify build
        run: ls -l
      - name: Deploy
        id: deploy
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # commit hash of v4.0.0
        if: github.ref == 'refs/heads/main'
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: prod
          exclude_assets: '.github,.gitignore,.vscode,docs,node_modules,src,package.json,package-lock.json,.nojekyll,assets/stylesheets/sass,assets/stylesheets/images/misc/demo.png'
          publish_dir: .
          cname: lynkos.dev
          full_commit_message: ${{ github.event.head_commit.message }}
          user_name: 'lynkos'
          user_email: 'kiwi2mii@gmail.com'